image: docker:latest

variables:
  DOCKER_IMAGE: "registry.gitlab.com/bryan13gallo/know_my_voice"

stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "
        cd /home/$SSH_USER/know_my_voice &&
        git pull origin main &&
        chmod +x setup.sh &&
        ./setup.sh"
    - ssh $SSH_USER@$SSH_HOST "docker pull $DOCKER_IMAGE:latest"
    - ssh $SSH_USER@$SSH_HOST "docker-compose down || true"
    - ssh $SSH_USER@$SSH_HOST "docker-compose up -d --force-recreate --no-deps web"
