image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_IMAGE: "registry.gitlab.com/bryan13gallo/know_my_voice"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build --no-cache -t $DOCKER_IMAGE:latest -f docker/Dockerfile .
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  only:
    - main
  before_script:
    # 📦 Prepare SSH for remote access
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts || true

  script:
    # ✅ Test SSH connection to the remote server
    - echo "🔹 Testing SSH connection..."
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo '✅ SSH connection successful'"

    # 🔄 Pull latest code on the remote server
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        cd /home/$SSH_USER/know_my_voice &&
        git reset --hard HEAD &&
        git pull origin main
      "

    # 🛠️ Generate the .env file dynamically
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        cd /home/$SSH_USER/know_my_voice &&
        echo \"# Django settings\" > .env &&
        echo \"DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY\" >> .env &&
        echo \"DJANGO_DEBUG=$DJANGO_DEBUG\" >> .env &&
        echo \"DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS\" >> .env &&
        echo \"\" >> .env &&
        echo \"# Database settings\" >> .env &&
        echo \"DATABASE_NAME=$DATABASE_NAME\" >> .env &&
        echo \"DATABASE_USER=$DATABASE_USER\" >> .env &&
        echo \"DATABASE_PASSWORD=$DATABASE_PASSWORD\" >> .env &&
        echo \"DATABASE_HOST=$DATABASE_HOST\" >> .env &&
        echo \"DATABASE_PORT=$DATABASE_PORT\" >> .env &&
        echo \".env file generated!\"
      "

    # ⬇️ Pull the latest Docker image
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        docker pull $DOCKER_IMAGE:latest
      "

    # 🚀 Restart Docker services safely without removing volumes
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        cd /home/$SSH_USER/know_my_voice &&
        docker-compose stop || true &&
        docker-compose pull &&
        docker-compose up -d --build --remove-orphans
      "
