# Generated by Django 3.2.10 on 2025-03-19 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('identification', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('name', models.CharField(max_length=128, verbose_name='Nombres completos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Numero de Télefono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está Activa')),
                ('judges', models.ManyToManyField(related_name='judges_rounds', to=settings.AUTH_USER_MODEL, verbose_name='Jueces')),
                ('participants', models.ManyToManyField(related_name='round', to='contest.Participant', verbose_name='Participantes')),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='RoundParticipantExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(null=True, verbose_name='Likes')),
                ('order', models.IntegerField(null=True, verbose_name='Orden')),
                ('rated', models.BooleanField(default=False, verbose_name='Calificado')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='contest.round')),
            ],
        ),
        migrations.CreateModel(
            name='RoundParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupling', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)], verbose_name='Acoplamiento en el Ritmo (35 pts)')),
                ('intonation', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)], verbose_name='Entonación Afinación (35 pts)')),
                ('expression', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Expresion e interpretación (30 pts)')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Juez')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_details', to='contest.round')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.township', verbose_name='Cantón'),
        ),
    ]
