# Generated by Django 3.2.10 on 2025-03-19 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='roundparticipant',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='roundparticipant',
            name='intonation',
        ),
        migrations.AddField(
            model_name='roundparticipant',
            name='presence',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Presencia (20 pts)'),
        ),
        migrations.AddField(
            model_name='roundparticipant',
            name='rhythm',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Ritmo (20 pts)'),
        ),
        migrations.AddField(
            model_name='roundparticipant',
            name='stage_performance',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Desempeño escénico (20 pts)'),
        ),
        migrations.AddField(
            model_name='roundparticipant',
            name='vocalization',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Vocalización (20 pts)'),
        ),
        migrations.AlterField(
            model_name='roundparticipant',
            name='coupling',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Acoplamiento a la pista musical (20 pts)'),
        ),
    ]
